name: build-action
on:
  workflow_call:
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
    inputs:
      aws-region:
        type: string
        required: true
      ecr-repository:
        type: string
        required: true
      tag:
        type: string
        required: true

jobs:
  build:
    runs-on: [ "self-hosted", "builder" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Gradle Clean
        run: ./gradlew clean assemble testClasses -isS
      - name: Gradle Check
        run: ./gradlew check -isS

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ inputs.aws-region }}
          aws-access-key-id: ${{ secrets.AWS-ACCESS-KEY-ID }}
          aws-secret-access-key: ${{ secrets.AWS-SECRET-ACCESS-KEY }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.ecr-repository }}
          IMAGE_TAG: ${{ inputs.tag }}
        run: |
          ./gradlew build
          ./gradlew jib -DIMAGE_NAME="$ECR_REGISTRY/$ECR_REPOSITORY" -DTAG_COMMIT=$IMAGE_TAG