name: kustomize-overlay-ssh
description: Kustomize Overlay in BitBucket

inputs:
  component-metadata:
    description: "Component metadata"
    required: true

  component-overlay:
    description: "Overlay to update"
    required: true
  
  component-tag:
    description: "New component tag"
    required: true
  
  aws-access-key-id:
    description: AWS Access key to access ECR repository
    required: true

  aws-secret-access-key:
    description: AWS Secret Access Key to access ECR repository
    required: true

  kustomize-repo:
    description: kustomize repository
    required: true

  kustomize-ssh-key:
    description: kustomize RW access SSH key
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ fromJson(inputs.component-metadata).ecr.region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registries: ${{ fromJson(inputs.component-metadata).ecr.registry }}

    - name: Update kustomize Overlay
      shell: bash
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ fromJson(inputs.component-metadata).ecr.repository }}
        KUSTOMIZE_SSH_KEY_FILE: ~/.ssh/id_kustomize_private_key
        KUSTOMIZE_SSH_KEY: ${{ inputs.kustomize-ssh-key }}
        KUSTOMIZE_PATH: ${{ fromJson(inputs.component-metadata).kustomize.path }}
        OVERLAY: ${{ inputs.component-overlay }}
      run: |
        # Prepare SSH
        echo ${KUSTOMIZE_SSH_KEY} >> ${KUSTOMIZE_SSH_KEY_FILE}
        chmod 600 ${KUSTOMIZE_SSH_KEY_FILE}
        export GII_SSH_COMMAND="ssh -i ${KUSTOMIZE_SSH_KEY_FILE}"
        cat <<EOF >> ~/.ssh/known_hosts
        bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
        github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
        EOF
        # End prepare SSH

        git clone ${{ inputs.kustomize-repo }} kustomize
        cd kustomize/${KUSTOMIZE_PATH}/overlays/${OVERLAY}
        kustomize edit set image ${ECR_REGISTRY}/${ECR_REPOSITORY}:${{ inputs.component-tag }}
        if ! git diff --quiet HEAD; then
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@hawk.ai"
          git add .
          git commit -m "AUTOMATIC JENKINS COMMIT: Update ${KUSTOMIZE_PATH}/overlays/${OVERLAY} for ${ECR_REPOSITORY} to ${{ env.HAWK_IMAGE_TAG }}"
          git push
        fi
